export const SERVICIOS_DATA = [
  {
    id: 'bateria',
    titulo: 'Reparación de Baterías',
    subtitulo: 'Baterías originales',
    icono: '🔋',
    descripcion: 'Cambio de baterías originales y de alta calidad con garantía',
    imagen: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600',
  },
  {
    id: 'pantalla',
    titulo: 'Reparación de Pantalla',
    subtitulo: 'LCD y OLED',
    icono: '📱',
    descripcion: 'Reemplazo de pantallas LCD y OLED con repuestos certificados',
    imagen: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=600',
  },
  {
    id: 'faceid',
    titulo: 'Reparación Face ID',
    subtitulo: 'Sensores faciales',
    icono: '🔐',
    descripcion: 'Reparación de sensores de reconocimiento facial y biométricos',
    imagen: 'https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=600',
  },
  {
    id: 'cristal-trasero',
    titulo: 'Cristal Trasero',
    subtitulo: 'Tapa trasera',
    icono: '🔨',
    descripcion: 'Cambio de tapa trasera y cristal con acabado original',
    imagen: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600',
  },
  {
    id: 'electronica',
    titulo: 'Reparaciones Electrónicas',
    subtitulo: 'Problemas técnicos',
    icono: '⚡',
    descripcion: 'Solución de problemas de carga, audio y conectividad',
    imagen: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600',
  },
  {
    id: 'memoria',
    titulo: 'Aumento de Memoria',
    subtitulo: 'Más almacenamiento',
    icono: '💾',
    descripcion: 'Expansión de almacenamiento interno de tu dispositivo',
    imagen: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600',
  },
  {
    id: 'camara',
    titulo: 'Cristal de Cámara',
    subtitulo: 'Lente de cámara',
    icono: '📷',
    descripcion: 'Reemplazo de cristal de lente de cámara principal y frontal',
    imagen: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600',
  },
  {
    id: 'auriculares',
    titulo: 'Reparación Auriculares',
    subtitulo: 'Audio y micrófono',
    icono: '🔊',
    descripcion: 'Reparación de auricular, altavoz y micrófono',
    imagen: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600',
  },
  {
    id: 'mantenimiento',
    titulo: 'Mantenimiento',
    subtitulo: 'Limpieza profunda',
    icono: '🛠️',
    descripcion: 'Limpieza y mantenimiento preventivo completo del equipo',
    imagen: 'https://images.unsplash.com/photo-1530319067432-f2a729c03db5?w=600',
  },
  {
    id: 'otras-fallas',
    titulo: 'Otras Fallas',
    subtitulo: 'Diagnóstico gratuito',
    icono: '🔧',
    descripcion: 'Diagnóstico y reparación de fallas diversas sin costo extra',
    imagen: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600',
  },
  {
    id: 'compra-venta',
    titulo: 'Compra y Venta',
    subtitulo: 'Celulares nuevos y usados',
    icono: '🛒',
    descripcion: 'Vendemos celulares nuevos y usados. También compramos tu equipo usado',
    imagen: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600',
  },
  {
    id: 'credito',
    titulo: 'Crédito Fácil',
    subtitulo: 'Financiación flexible',
    icono: '💳',
    descripcion: 'Opciones de crédito con Addi, Sistecredito y Cupo Brilla',
    imagen: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600',
  },
];
